import { CrimeType } from '@/service/report.service';
import { VerificationCrimeReport, VerificationLevel } from '@/types/map';

export const SAMPLE_DATA: VerificationCrimeReport[] = [
    {
        id: 'uuid-1',
        title: 'Cướp giật tại chợ Bến Thành',
        description: 'Bị cướp giật điện thoại, có video camera an ninh ghi lại...',
        type: CrimeType.CUOP_GIAT,
        lat: 10.7721,
        lng: 106.6983,
        address: 'Chợ Bến Thành, Quận 1, TP.HCM',
        district: 'Quận 1',
        province: 'Hồ Chí Minh',
        status: 1,
        severity: 5,
        severityLevel: 'high',
        trustScore: 90,
        verificationLevel: VerificationLevel.CONFIRMED,
        confirmationCount: 12,
        disputeCount: 0,
        attachments: [
            'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Ben_Thanh_Market_-_front_view.jpg/1200px-Ben_Thanh_Market_-_front_view.jpg',
        ],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'uuid-2',
        title: 'Mất xe máy (Chưa xác minh)',
        description: 'Tôi để xe ở đây 5 phút quay lại thì mất...',
        type: CrimeType.TROM_CAP,
        lat: 10.7952,
        lng: 106.7218,
        address: 'Landmark 81, Bình Thạnh',
        district: 'Bình Thạnh',
        province: 'Hồ Chí Minh',
        status: 1,
        severity: 3,
        severityLevel: 'medium',
        trustScore: 25,
        verificationLevel: VerificationLevel.UNVERIFIED,
        confirmationCount: 0,
        disputeCount: 1,
        attachments: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'uuid-3',
        title: 'Móc túi phố đi bộ',
        description: 'Đông người chen lấn, bị móc ví khi xem biểu diễn.',
        type: CrimeType.TROM_CAP,
        lat: 10.7745,
        lng: 106.7032,
        address: 'Phố đi bộ Nguyễn Huệ, Quận 1',
        district: 'Quận 1',
        province: 'Hồ Chí Minh',
        status: 1,
        severity: 2,
        severityLevel: 'low',
        trustScore: 55,
        verificationLevel: VerificationLevel.PENDING,
        confirmationCount: 3,
        disputeCount: 0,
        attachments: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

